.text

.global add16
/* Eingabe:
 *    a in r25:r24
 *    b in r23:r22
 * Ausgabewert in r25:r24
 */
add16:
    /* TODO */
    ret

.global shl16
/* Eingabe: a in r25:r24
 * Ausgabewert in r25:r24
 */
shl16:
    /* TODO */
    ret

.global mult8_8
/* Eingabe:
 *    a in r24
 *    b in r22
 * Ausgabewert in r25:r24
 */
 mult8_8:
    /* TODO */
    ret

.global multu8_16
/* Eingabe:
 *    a in r24
 *    b in r23:r22
 * Ausgabewert in r25:r22
 */
multu8_16:
    /* TODO */
    ret

.global multu16_16
/* Eingabe:
 *    a in r25:r24
 *    b in r23:r22
 * Ausgabewert in r25:r22
 */
multu16_16:
    /* TODO */
    ret